platform :ios, '14.0'

inhibit_all_warnings!
set_arc_compatibility_flag!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'AirLockSDK_Example' do
  pod 'AirLockSDK',     :path => '../'
  pod 'Alamofire',      '5.4.3'
  pod 'SwiftyJSON',     '~> 5.0.0'
end


