
inhibit_all_warnings!
set_arc_compatibility_flag!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'AirLockSDK_Example' do
  pod 'AirLockSDK',     :path => '../'
  pod 'Alamofire',      '~> 5.0.0-beta.6'
  pod 'SwiftyJSON',     '~> 5.0.0'

  target 'AirLockSDK_Tests' do
    inherit!            :search_paths
  end
end


